# Generated by Django 3.2.7 on 2021-09-10 10:37

from django.db import migrations, models
import user_management.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True, validators=[user_management.validators.email_validator], verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, validators=[user_management.validators.first_name_validate])),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, validators=[user_management.validators.last_name_validate])),
                ('password', models.CharField(max_length=40, validators=[user_management.validators.password_validate])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
