# Generated by Django 3.2.7 on 2021-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
