# Generated by Django 3.2.7 on 2021-09-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('middleware', '0002_auto_20210910_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middleware.ipaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ip_d',
            },
        ),
    ]
